name: CICD on Selfhosted Runner 
on: push
jobs:
  CICD-job:
   continue-on-error: true 
   runs-on: self-hosted
   steps:
   - name: Checkout code on the VM
     uses: actions/checkout@v7
   - name: Install Java 
     uses: actions/setup-java@v5
      with:
       distribution: temurin
       java-version: '17'
   - name: Setup Docker 
     run: sudo apt update && sudo apt install docker.io -y
   - name: Build the code 
     run: mvn package 
   - name: Build the dockerfile to build Image 
     run: docker build -t myimagecicd .
   - name: Build the container and deploy the application 
     run: docker run -d -P myimagecicd
