name: CI with java using maven
on: push

jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7
        
      - name: Install Java and Maven
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: complie code
        run: mvn compile

      - name: Test the code
        run: mvn test

      - name: Package the code 
        run: mvn package
      
